colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Rockfordia
layout_spectrum: 0.8175268662162125
typography_spectrum: 0.9497349099256098
color:
  brandStrength: 0.7177995997481048
  lightness: 0.9914760023821145
  saturation: 0.40764925023540854
  rhythmicContrast: 0.9958224045112729
  brandColors:
    - '#334D5C'
    - '#45B29D'
    - '#EFC94C'
    - '#E27A3F'
    - '#DF5A49'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F_Yp6X1jHU14%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D_Yp6X1jHU14&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F_Yp6X1jHU14%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Go Rockford
          url: 'https://www.youtube.com/user/gorockfordregion'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - rockford
        - duration
        - views
        - illinois
        - uic
        - live
        - things
        - pocket
        - amazing
        - stroll
      description: >-
        At the Rockford Area Convention & Visitors Bureau, we love inviting the
        world to visit us. Rockford is a great place to visit and believe us
        it's also an amazing place to live. Visit www.GoRockford.com for a
        glimpse into the daily lives of those of us lucky enough to live in
        Real.
      inLanguage: en
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=_Yp6X1jHU14&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=_Yp6X1jHU14&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=_Yp6X1jHU14&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=_Yp6X1jHU14&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=_Yp6X1jHU14&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=_Yp6X1jHU14'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=_Yp6X1jHU14
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=_Yp6X1jHU14
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/_Yp6X1jHU14'
      title: 'Rockford, Illinois -- In Good Company'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Rockfordia
description: ''
github: true
url: 'https://rockfordia.com'
purpose:
  - type: external
    url: 'https://domains.rockfordia.com'
    label: Buy a Domain Name
